spring:
  datasource:
    url: jdbc:mysql://xxx/securityDB?characterEncoding=UTF-8&&serverTimezone=Asia/Shanghai&&autoReconnect=true&&failOverReadOnly=false
    username: root
    password: xxx
  profiles:
    active: dev

